npm i --save i18next
npm i --save i18next-browser-languagedetector
npm i --save i18next-http-backend
npm i --save immer
npm i --save node-sass
npm i --save react
npm i --save react-dom
npm i --save react-i18next
npm i --save react-redux
npm i --save react-router-dom
npm i --save redux

npm i --save-d @babel/core
npm i --save-d @babel/preset-env
npm i --save-d @babel/preset-react
npm i --save-d babel-eslint
npm i --save-d babel-jest
npm i --save-d babel-loader
npm i --save-d css-loader
npm i --save-d file-loader
npm i --save-d jest
npm i --save-d react-test-renderer
npm i --save-d sass-loader
npm i --save-d snazzy
npm i --save-d standard
npm i --save-d style-loader
npm i --save-d webpack
npm i --save-d webpack-cli
npm i --save-d webpack-dev-server